export const  GET_API_ORIGINALS = "GET_API_ORIGINALS";
export const GET_API_TRENDING ="GET_API_TRENDING";
export const GET_API_TOPRATED = "GET_API_TOPRATED";
export const GET_API_ACTION = "GET_API_ACTION";
export const GET_API_COMEDY = "GET_API_COMEDY";
export const GET_API_HORROR = "GET_API_HORROR";
export const GET_API_ROMANCE = "GET_API_ROMANCE";
export const GET_API_DOCUMENTARIES = " GET_API_DOCUMENTARIES";

export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";

export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";